apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: refactorspacesconfigs.eks.amazonaws.com
spec:
  scope: Namespaced
  group: eks.amazonaws.com
  names:
    kind: RefactorSpacesConfig
    plural: refactorspacesconfigs
    singular: refactorspacesconfig
    shortNames:
      - rscs
      - rsc
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties: 
                environmentIdentifier: 
                  type: string
                applicationIdentifier: 
                  type: string
                vpcId: 
                  type: string
                reconciliation:
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                state:
                  x-kubernetes-preserve-unknown-fields: true
                  type: string
                services:
                  type: array
                  x-kubernetes-preserve-unknown-fields: true
                  items:
                    type: string
      subresources:
        status: {}